var namespace_galactic_intersection =
[
    [ "App", "class_galactic_intersection_1_1_app.html", "class_galactic_intersection_1_1_app" ],
    [ "Dozer", "class_galactic_intersection_1_1_dozer.html", "class_galactic_intersection_1_1_dozer" ],
    [ "EnemyProjectile", "class_galactic_intersection_1_1_enemy_projectile.html", "class_galactic_intersection_1_1_enemy_projectile" ],
    [ "EnemyShip", "class_galactic_intersection_1_1_enemy_ship.html", "class_galactic_intersection_1_1_enemy_ship" ],
    [ "EnemyShipSpawner", "class_galactic_intersection_1_1_enemy_ship_spawner.html", "class_galactic_intersection_1_1_enemy_ship_spawner" ],
    [ "GameFrameworkElement", "class_galactic_intersection_1_1_game_framework_element.html", "class_galactic_intersection_1_1_game_framework_element" ],
    [ "GameMechanics", "class_galactic_intersection_1_1_game_mechanics.html", "class_galactic_intersection_1_1_game_mechanics" ],
    [ "GameObject", "class_galactic_intersection_1_1_game_object.html", "class_galactic_intersection_1_1_game_object" ],
    [ "GruntFighter", "class_galactic_intersection_1_1_grunt_fighter.html", "class_galactic_intersection_1_1_grunt_fighter" ],
    [ "Gunship", "class_galactic_intersection_1_1_gunship.html", "class_galactic_intersection_1_1_gunship" ],
    [ "IDecideWhatToDo", "interface_galactic_intersection_1_1_i_decide_what_to_do.html", "interface_galactic_intersection_1_1_i_decide_what_to_do" ],
    [ "IMove", "interface_galactic_intersection_1_1_i_move.html", "interface_galactic_intersection_1_1_i_move" ],
    [ "MainWindow", "class_galactic_intersection_1_1_main_window.html", "class_galactic_intersection_1_1_main_window" ],
    [ "MovingObject", "class_galactic_intersection_1_1_moving_object.html", "class_galactic_intersection_1_1_moving_object" ],
    [ "MultiShooterEnemy", "class_galactic_intersection_1_1_multi_shooter_enemy.html", "class_galactic_intersection_1_1_multi_shooter_enemy" ],
    [ "PlayerProjectile", "class_galactic_intersection_1_1_player_projectile.html", "class_galactic_intersection_1_1_player_projectile" ],
    [ "PlayerProjectileSpawner", "class_galactic_intersection_1_1_player_projectile_spawner.html", "class_galactic_intersection_1_1_player_projectile_spawner" ],
    [ "PlayerShip", "class_galactic_intersection_1_1_player_ship.html", "class_galactic_intersection_1_1_player_ship" ],
    [ "PowerUp", "class_galactic_intersection_1_1_power_up.html", "class_galactic_intersection_1_1_power_up" ],
    [ "PowerUpSpawner", "class_galactic_intersection_1_1_power_up_spawner.html", "class_galactic_intersection_1_1_power_up_spawner" ],
    [ "Reaper", "class_galactic_intersection_1_1_reaper.html", "class_galactic_intersection_1_1_reaper" ],
    [ "Ship", "class_galactic_intersection_1_1_ship.html", "class_galactic_intersection_1_1_ship" ]
];